config/routes.rb
Projectiv::Application.routes.draw do

  match 'about' => 'welcome#about'

  root :to => 'welcome#home'

  resources :projects do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project
  attr_accessible :body, :name
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :body, :name, :title

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.build(params[:comment])

    if @comment.save
      flash[:notice] = "Your comment was saved."
      redirect_to @project
    else
      flash[:error] = "Your comment wasn't saved. Please try again."
      render :new
      # SPINACH we do not know about this render
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @comment = @project.comments.find(params[:id])

    if @comment.destroy
      flash[:notice] = "Your comment was deleted"
      redirect_to @project
    else
      flash[:error] = "Your comment wasn't deleted. Please try again."
      redirect_to @project
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      flash[:notice]= "Your project was saved"
      redirect_to @project
    else
      flash[:error]= "Your project wasn't saved. Please try again"
      render :new
    end
  end

  def edit
  end

  def show
    @project = Project.find(params[:id])
    @comments = @project.comments
    @comment = Comment.new
  end

  def index
    @projects = Project.all
    @project = Project.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<!-- Each submitted comment has a body and name (of the user who submits it). -->
<%= comment.body %>
submitted by <%= comment.name %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projectiv</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  To change the navbar, go to app/views/layouts/application.html.erb

  <!-- This is the code for the navbar, you can change the titles of the links ("home", "about") -->
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Popular Projects", projects_path %></li>
    <li><%= link_to "New Projects", projects_path %></li>
  </ul>

<%= yield %>

</div>

</body>
</html>

app/views/projects/_project.html.erb
<!-- Each submitted project has a title, name and body. -->

<%= link_to project.title, project %>
<%= project.body %>
submitted by <%= project.name %>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>



<!-- This displays all of the projects. To change the way projects appear, go to app/views/projects/_project -->
<%= render partial: 'projects/project', collection: @projects %>



<!-- This is the form for creating new projects -->
<%= form_for @project do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit "Save" %>
<% end %>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
Find me in app/views/projects/show

<%= @project.title %>
<%= @project.body %>
Submitted by <%= @project.name %>


<!-- This displays all of the comments for this particular project. To change the way comments appear, go to app/views/comments/_comment -->
<%= render partial: 'comments/comment', collection: @comments %>



<!-- This is the form for users to create and submit a new comment -->
<%= form_for [@project, @comment] do |f| %>
<%= f.label :body %>
<%= f.text_area :body %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit "Save" %>
<% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>